export enum CARD_TYPE {
  VISA = "Visa",
  VISA_ELECTRON = "Visa Electron",
  MASTERCARD = "MasterCard",
  AMERICAN_EXPRESS = "American Express",
  DISCOVER = "Discover",
  DINERS_CLUB = "Diners Club",
  DINERS_CLUB_US_CANADA = "Diners Club United States & Canada",
  JCB = "JCB",
  CHINA_UNIONPAY = "China UnionPay",
  CHINA_T_UNION = "China T-Union",
  INTERPAYMENT = "InterPayment",
  INSTAPAYMENT = "InstaPayment",
  MAESTRO = "Maestro",
  MAESTRO_UK = "Maestro UK",
  DANKORT = "Dankort",
  MIR = "Mir",
  BORICA = "BORICA",
  TROY = "Troy",
  UATP = "UATP",
  VERVE = "Verve",
  LANKAPAY = "LankaPay",
  UZCARD = "Uzcard",
  HUMO = "HUMO",
  GPN = "GPN",
  UKRCART = "UkrCart",
  UNKNOWN = "Unknown",
}
